#!/usr/bin/env python

import sys

from rqt_evo.evo import Evo
from rqt_gui.main import Main

plugin = 'rqt_evo'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin)) # , plugin_argument_provider=Evo.add_arguments
